# Generated by Django 5.2.9 on 2026-01-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'campaign_occasion',
                'ordering': ['display_order'],
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='auto_statement_url',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='documents_urls',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='featured_order',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='share_count',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='tags',
        ),
        migrations.AddField(
            model_name='campaign',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='admin_panel.campaignoccasion'),
        ),
        migrations.CreateModel(
            name='TargetProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='admin_panel.organization')),
            ],
            options={
                'db_table': 'target_program',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='admin_panel.targetprogram'),
        ),
    ]
