# Generated by Django 5.2.9 on 2026-01-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_campaign_approved_at_campaign_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetprogram',
            options={'verbose_name': 'Chương trình mục tiêu', 'verbose_name_plural': 'Danh sách Chương trình mục tiêu'},
        ),
        migrations.AddField(
            model_name='targetprogram',
            name='beneficiary_address',
            field=models.TextField(default='', help_text='Địa chỉ nơi cần giúp đỡ (VD: Điểm trường X, Xã Y, Huyện Z...)', verbose_name='Địa chỉ thụ hưởng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='targetprogram',
            name='beneficiary_lat',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Vĩ độ (Latitude)', max_digits=10, null=True, verbose_name='Vĩ độ'),
        ),
        migrations.AddField(
            model_name='targetprogram',
            name='beneficiary_lng',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Kinh độ (Longitude)', max_digits=11, null=True, verbose_name='Kinh độ'),
        ),
        migrations.AddField(
            model_name='targetprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='programs/', verbose_name='Ảnh bìa'),
        ),
        migrations.AddField(
            model_name='targetprogram',
            name='total_target_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng số tiền cần (VNĐ)'),
        ),
        migrations.AlterField(
            model_name='targetprogram',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='targetprogram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Hiển thị'),
        ),
        migrations.AlterField(
            model_name='targetprogram',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên chương trình'),
        ),
    ]
