# Generated by Django 5.2.9 on 2026-01-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_alter_targetprogram_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='campaign',
            name='beneficiary_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='beneficiary_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='current_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đã đạt'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('active', 'Đang gây quỹ'), ('completed', 'Đã hoàn thành'), ('ended', 'Đã kết thúc'), ('paused', 'Tạm dừng'), ('rejected', 'Bị từ chối'), ('hidden', 'Đã ẩn'), ('deleted', 'Đã xóa')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Mục tiêu'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Tên chiến dịch'),
        ),
    ]
