# Generated by Django 5.2.9 on 2026-01-27 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_campaign_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản quản lý'),
        ),
        migrations.AddField(
            model_name='targetprogram',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã được Admin duyệt'),
        ),
        migrations.AddField(
            model_name='targetprogram',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='program_docs/', verbose_name='Hồ sơ minh chứng (PDF/Ảnh)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Đã xác thực'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên tổ chức'),
        ),
    ]
