# Generated by Django 5.2.9 on 2026-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_organization_manager_targetprogram_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='previous_hash',
            field=models.CharField(default='0', editable=False, max_length=64),
        ),
    ]
