# Generated by Django 5.2.9 on 2026-02-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_donation_hash_donation_previous_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='donation',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('vietqr', 'VietQR'), ('vnpay', 'VNPay'), ('bank_transfer', 'Bank Transfer')], default='bank_transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='previous_hash',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
