# Generated by Django 5.2.9 on 2026-02-04 13:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_donation_amount_alter_donation_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='eth_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch Blockchain'),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_blockchain_synced',
            field=models.BooleanField(default=False, verbose_name='Đã ghi lên Etherscan'),
        ),
        migrations.CreateModel(
            name='CampaignDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền đã chi')),
                ('title', models.CharField(max_length=255, verbose_name='Khoản chi (VD: Mua 100 bao gạo)')),
                ('description', models.TextField(verbose_name='Chi tiết chi tiêu')),
                ('recipient_name', models.CharField(max_length=255, verbose_name='Đơn vị thụ hưởng (VD: Cty Gạo A)')),
                ('recipient_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Liên hệ thụ hưởng')),
                ('proof_images', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name='Ảnh hóa đơn/Chứng từ')),
                ('proof_document_url', models.TextField(blank=True, null=True, verbose_name='Link file PDF/Excel (nếu có)')),
                ('eth_tx_hash', models.CharField(blank=True, max_length=100, null=True, verbose_name='TxHash Blockchain')),
                ('status', models.CharField(choices=[('pending', 'Chờ kiểm duyệt'), ('verified', 'Đã xác thực'), ('rejected', 'Từ chối'), ('on_chain', 'Đã ghi Blockchain')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, null=True, verbose_name='Ghi chú của Admin')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='admin_panel.campaign')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người báo cáo')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_disbursements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo cáo Giải ngân',
                'verbose_name_plural': 'Danh sách Giải ngân',
                'db_table': 'campaign_disbursement',
            },
        ),
    ]
