# Generated by Django 5.2.9 on 2026-03-10 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_donation_eth_tx_hash_donation_is_blockchain_synced_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approval_threshold_pct',
            field=models.IntegerField(default=51),
        ),
        migrations.AddField(
            model_name='campaign',
            name='disbursed_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='locked_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voting_power_cap_pct',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='campaigndisbursement',
            name='actual_lat',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='campaigndisbursement',
            name='actual_lng',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='campaigndisbursement',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='gas_fee_eth',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='gas_fee_vnd',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='DisbursementProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount_requested', models.DecimalField(decimal_places=0, max_digits=15)),
                ('description', models.TextField()),
                ('evidence_url', models.TextField()),
                ('status', models.CharField(default='voting', max_length=20)),
                ('end_date', models.DateTimeField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='admin_panel.campaign')),
            ],
            options={
                'db_table': 'disbursement_proposal',
            },
        ),
        migrations.AddField(
            model_name='campaigndisbursement',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.disbursementproposal'),
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_agree', models.BooleanField(default=True)),
                ('voting_power', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='admin_panel.disbursementproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposal_vote',
                'unique_together': {('proposal', 'user')},
            },
        ),
    ]
