# Generated by Django 6.0.2 on 2026-03-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_bankstatement_source_alter_bankstatement_options'),
        ('admin_panel', '0010_campaign_approval_threshold_pct_and_more'),
    ]

    operations = [
    ]
