# Generated by Django 6.0.2 on 2026-03-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_disbursement_gas_tracking'),
        ('admin_panel', '0014_donation_admin_gas_fee_wei'),
    ]

    operations = [
    ]
