# Generated by Django 6.0.2 on 2026-03-31 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_merge_20260330_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='admin_gas_fee_wei',
        ),
    ]
