# Generated by Django 6.0.2 on 2026-04-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0017_donation_admin_send_eth_gas_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='admin_funding_status',
            field=models.CharField(blank=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='init_campaign_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TxHash initCampaign'),
        ),
    ]
