# Generated by Django 6.0.2 on 2026-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_donation_admin_funding_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='blockchain_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='blockchain_error',
            field=models.TextField(blank=True, null=True, verbose_name='Lỗi blockchain gần nhất'),
        ),
        migrations.AddField(
            model_name='donation',
            name='blockchain_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donation',
            name='blockchain_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='blockchain_status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý blockchain'), ('confirmed', 'Đã xác nhận trên blockchain'), ('failed', 'Thất bại')], default='pending', max_length=20, verbose_name='Trạng thái blockchain'),
        ),
    ]
