# Generated by Django 6.0.2 on 2026-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_donation_blockchain_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='bank_record_gas_vnd',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='bank_record_gas_wei',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='bank_record_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tx recordBankDonation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='donate_onbehalf_gas_vnd',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donate_onbehalf_gas_wei',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donate_onbehalf_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tx donateOnBehalf'),
        ),
        migrations.AddField(
            model_name='donation',
            name='record_gascost_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tx recordGasCost'),
        ),
        migrations.AddField(
            model_name='donation',
            name='total_admin_gas_vnd',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='total_admin_gas_wei',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='send_eth_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tx Admin cap ETH (legacy)'),
        ),
    ]
