# Generated by Django 6.0.2 on 2026-05-04 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0020_donation_bank_record_gas_vnd_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='vnpay_transaction_no',
        ),
        migrations.AddField(
            model_name='donation',
            name='order_code',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='PayOS orderCode'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payos_checkout_url',
            field=models.TextField(blank=True, null=True, verbose_name='PayOS checkout URL'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payos_paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm PayOS xác nhận thanh toán'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payos_payment_link_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayOS payment link ID'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payos_qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='PayOS QR code'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payos_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayOS reference'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payos_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayOS transaction ID'),
        ),
        migrations.AddField(
            model_name='donation',
            name='payos_webhook_received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm nhận webhook PayOS'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_verified_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Admin xác thực ngân hàng'),
        ),
        migrations.AddField(
            model_name='organization',
            name='bank_verified_by_admin',
            field=models.BooleanField(default=False, verbose_name='Ngân hàng đã xác thực'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do từ chối KYC'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kyc_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='kyc_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_kyc', to=settings.AUTH_USER_MODEL, verbose_name='Admin duyệt KYC'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kyc_status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã nộp hồ sơ'), ('under_review', 'Đang thẩm định'), ('approved', 'Đã duyệt KYC'), ('rejected', 'Từ chối KYC'), ('suspended', 'Tạm khóa')], default='draft', max_length=20, verbose_name='Trạng thái KYC'),
        ),
        migrations.AddField(
            model_name='organization',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='wallet_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='wallet_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_verified_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Admin xác thực ví'),
        ),
        migrations.AddField(
            model_name='organization',
            name='wallet_verified_by_admin',
            field=models.BooleanField(default=False, verbose_name='Ví đã xác thực'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('payos', 'PayOS'), ('vietqr', 'VietQR'), ('bank_transfer', 'Bank Transfer')], default='bank_transfer', max_length=20),
        ),
    ]
