# Generated by Django 6.0.2 on 2026-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_remove_donation_vnpay_transaction_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='eoa_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smart_account_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
