# Generated by Django 6.0.2 on 2026-05-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_userprofile_eoa_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementproposal',
            name='ipfs_cid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IPFS CID hóa đơn'),
        ),
    ]
