# Generated by Django 6.0.2 on 2026-05-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0023_disbursementproposal_ipfs_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementproposal',
            name='admin_approval_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TxHash duyệt của Admin'),
        ),
        migrations.AddField(
            model_name='disbursementproposal',
            name='admin_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementproposal',
            name='approval_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Số chữ ký đã đồng bộ'),
        ),
        migrations.AddField(
            model_name='disbursementproposal',
            name='last_approval_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disbursementproposal',
            name='supervisor_approval_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='TxHash duyệt của Supervisor'),
        ),
        migrations.AddField(
            model_name='disbursementproposal',
            name='supervisor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
