# Generated by Django 6.0.2 on 2026-05-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0024_disbursementproposal_admin_approval_tx_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_sybil',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='sybil_flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
