# Generated by Django 6.0.2 on 2026-05-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_v3_disbursement_eip712'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='payos_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayOS API Key'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payos_checksum_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayOS Checksum Key'),
        ),
        migrations.AddField(
            model_name='organization',
            name='payos_client_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayOS Client ID'),
        ),
    ]
