# Generated by Django 6.0.2 on 2026-05-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_organization_payos_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementproposal',
            name='payos_checkout_url',
            field=models.TextField(blank=True, null=True, verbose_name='PayOS Checkout URL (cached)'),
        ),
        migrations.AddField(
            model_name='disbursementproposal',
            name='payos_payment_link_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PayOS Payment Link ID'),
        ),
    ]
