# Generated by Django 6.0.2 on 2026-05-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_disbursementproposal_payos_checkout_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementproposal',
            name='payos_order_code',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='PayOS Order Code (for webhook lookup)'),
        ),
    ]
