# Generated by Django 5.2.9 on 2026-06-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_campaign_beneficiary_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã số thuế'),
        ),
    ]
