# Generated by Django 6.0.2 on 2026-06-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_organization_tax_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_protected_beneficiary',
            field=models.BooleanField(default=False, verbose_name='Bảo vệ người thụ hưởng'),
        ),
    ]
