# Generated by Django 6.0.2 on 2026-06-05 06:25

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_campaign_is_protected_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=255, verbose_name='Tên thật người thụ hưởng')),
                ('beneficiary_age', models.IntegerField(blank=True, null=True, verbose_name='Tuổi/Năm sinh')),
                ('story', models.TextField(verbose_name='Câu chuyện chi tiết')),
                ('images_urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, verbose_name='Danh sách link ảnh hoàn cảnh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='admin_panel.campaign', verbose_name='Chiến dịch')),
            ],
            options={
                'verbose_name': 'Chi tiết hoàn cảnh',
                'verbose_name_plural': 'Chi tiết hoàn cảnh',
                'db_table': 'campaign_detail',
            },
        ),
    ]
