# Generated by Django 6.0.2 on 2026-06-06 02:06

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_campaign_avatar_image_campaign_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='payos_api_key',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='payos_checksum_key',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='payos_client_id',
        ),
        migrations.AddField(
            model_name='organization',
            name='founding_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày thành lập'),
        ),
        migrations.AddField(
            model_name='organization',
            name='headquarters_address',
            field=models.TextField(blank=True, null=True, verbose_name='Địa chỉ trụ sở chính'),
        ),
        migrations.AddField(
            model_name='organization',
            name='mission_statement',
            field=models.TextField(blank=True, null=True, verbose_name='Tuyên bố sứ mệnh'),
        ),
        migrations.AddField(
            model_name='organization',
            name='operating_license_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số giấy phép hoạt động'),
        ),
        migrations.AddField(
            model_name='organization',
            name='social_media_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link mạng xã hội'),
        ),
        migrations.CreateModel(
            name='OrganizationRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('position', models.CharField(max_length=255, verbose_name='Chức vụ')),
                ('id_card_number', models.CharField(max_length=50, unique=True, verbose_name='Số CCCD/CMND')),
                ('id_card_date', models.DateField(verbose_name='Ngày cấp CCCD/CMND')),
                ('id_card_place', models.CharField(max_length=255, verbose_name='Nơi cấp CCCD/CMND')),
                ('phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('permanent_address', models.TextField(verbose_name='Địa chỉ thường trú')),
                ('authorization_letter', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw')),
                ('id_card_front', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('id_card_back', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='admin_panel.organization')),
            ],
            options={
                'verbose_name': 'Đại diện tổ chức',
                'verbose_name_plural': 'Đại diện tổ chức',
                'db_table': 'organization_representative',
            },
        ),
    ]
