# Generated by Django 6.0.2 on 2026-06-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0039_backfill_legacy_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursementproposal',
            name='post_proof_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Dữ liệu ảnh và mô tả từng ảnh'),
        ),
        migrations.AddField(
            model_name='disbursementproposal',
            name='post_proof_general_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả chung minh chứng sau giải ngân'),
        ),
        migrations.AddField(
            model_name='disbursementproposal',
            name='post_proof_ipfs_cid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='IPFS CID minh chứng sau giải ngân'),
        ),
    ]
