# Generated by Django 5.2.9 on 2026-07-13 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0040_disbursementproposal_post_proof_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='supervisor_kyc_status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('submitted', 'Đã nộp hồ sơ'), ('under_review', 'Đang thẩm định'), ('approved', 'Đã duyệt KYC'), ('rejected', 'Từ chối KYC'), ('suspended', 'Tạm khóa')], default='draft', max_length=20, verbose_name='Trạng thái duyệt của Giám sát'),
        ),
        migrations.AddField(
            model_name='organization',
            name='supervisor_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do Giám sát từ chối KYC'),
        ),
        migrations.AddField(
            model_name='organization',
            name='supervisor_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='supervisor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_reviewed_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Giám sát duyệt KYC'),
        ),
    ]
