"""
Django settings for doantn project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

cloudinary.config(
    cloud_name='dqenme54s',
    api_key='564825335397356',
    api_secret='nZKOb2ozXzANNjQrQwhUcuOjcT4',
    secure=True
)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6rplghlbtk@kvo9!_ej&c%m2zm-abxem7g49_*u=-v=2)e!)6h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
	'django.contrib.postgres',
    'admin_panel',
    'client',
    'cloudinary',
]

# Google OAuth settings
GOOGLE_CLIENT_ID = '954026297024-os892lmsgj1p0h5s6vuglm2a98mvl199.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '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'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'doantn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'doantn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# settings.py
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres', 
        'USER': 'postgres',
        'PASSWORD': '280404',
        'HOST': 'db.rxstrczguuazkurpmarw.supabase.co',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/admin/dangnhap/'
LOGIN_REDIRECT_URL = '/admin/trangchu/'
LOGOUT_REDIRECT_URL = '/admin/dangnhap/'


# settings.py

# =====================================================
# VNPAY CONFIGURATION (Sandbox)
# =====================================================
VNPAY_TMN_CODE = 'MF33GH9Q'
VNPAY_HASH_SECRET = 'BNVN2FS7QZM6FVZS8L0C29DXPIIMNVBG'
VNPAY_URL = 'https://sandbox.vnpayment.vn/paymentv2/vpcpay.html'
SITE_URL = 'http://localhost:8000'

# =====================================================
# CASSO / SEPAY WEBHOOK SECRET
# =====================================================
CASSO_SECRET_KEY = 'my-casso-secret-key-2024'

# =====================================================
# BLOCKCHAIN CONFIGURATION
# =====================================================
# 1. Địa chỉ Smart Contract (Bạn vừa copy lúc nãy)
SMART_CONTRACT_ADDRESS = "0x1bc9857B478346940CCfF4565dF0aaBeBd899f8B"

# 2. Private Key ví MetaMask (Cái mã dài ngoằng bạn lấy trong Account Details)
# LƯU Ý: Tuyệt đối không lộ mã này cho ai.
WALLET_PRIVATE_KEY = "eb85174ee3d25a204dd7316f5c3ccc5b79a7df4c9bd0b2235fca1e0372691412" 

# 3. Địa chỉ ví Admin (Địa chỉ công khai 0x...)
WALLET_ADDRESS = "0x052a16A4bC4304a3CD7178ECfac895Fd8B1f059D"

# 4. Đường dẫn mạng Sepolia (RPC URL)
# Bạn có thể dùng link public này để test, hoặc đăng ký Infura/Alchemy cho ổn định
WEB3_PROVIDER_URL = "https://ethereum-sepolia-rpc.publicnode.com" 

# 5. Mã ABI (Copy từ Remix dán vào đây, để 1 dòng dài hoặc enter xuống dòng đều được)
SMART_CONTRACT_ABI = [
	{
		"inputs": [],
		"stateMutability": "nonpayable",
		"type": "constructor"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": True,
				"internalType": "uint256",
				"name": "cid",
				"type": "uint256"
			},
			{
				"indexed": False,
				"internalType": "address",
				"name": "orgAddress",
				"type": "address"
			},
			{
				"indexed": False,
				"internalType": "string",
				"name": "orgName",
				"type": "string"
			}
		],
		"name": "CampaignCreated",
		"type": "event"
	},
	{
		"inputs": [],
		"name": "depositExchangePool",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": True,
				"internalType": "uint256",
				"name": "cid",
				"type": "uint256"
			},
			{
				"indexed": False,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			},
			{
				"indexed": False,
				"internalType": "address",
				"name": "recipient",
				"type": "address"
			}
		],
		"name": "Disbursed",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_cid",
				"type": "uint256"
			}
		],
		"name": "donate",
		"outputs": [],
		"stateMutability": "payable",
		"type": "function"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": True,
				"internalType": "uint256",
				"name": "cid",
				"type": "uint256"
			},
			{
				"indexed": True,
				"internalType": "address",
				"name": "donor",
				"type": "address"
			},
			{
				"indexed": False,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			}
		],
		"name": "Donated",
		"type": "event"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": False,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			},
			{
				"indexed": False,
				"internalType": "uint256",
				"name": "newBalance",
				"type": "uint256"
			}
		],
		"name": "ExchangePoolDeposited",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_cid",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "_amount",
				"type": "uint256"
			}
		],
		"name": "executeDisbursement",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": True,
				"internalType": "uint256",
				"name": "cid",
				"type": "uint256"
			},
			{
				"indexed": False,
				"internalType": "uint256",
				"name": "amount",
				"type": "uint256"
			}
		],
		"name": "GasRecovered",
		"type": "event"
	},
	{
		"anonymous": False,
		"inputs": [
			{
				"indexed": True,
				"internalType": "uint256",
				"name": "cid",
				"type": "uint256"
			},
			{
				"indexed": False,
				"internalType": "address",
				"name": "user",
				"type": "address"
			},
			{
				"indexed": False,
				"internalType": "uint256",
				"name": "amountG",
				"type": "uint256"
			}
		],
		"name": "GasSubsidized",
		"type": "event"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_cid",
				"type": "uint256"
			},
			{
				"internalType": "string",
				"name": "_orgName",
				"type": "string"
			},
			{
				"internalType": "address payable",
				"name": "_orgAddress",
				"type": "address"
			}
		],
		"name": "initCampaign",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_cid",
				"type": "uint256"
			},
			{
				"internalType": "address payable",
				"name": "_user",
				"type": "address"
			},
			{
				"internalType": "uint256",
				"name": "_amountE",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "_amountG",
				"type": "uint256"
			}
		],
		"name": "sendEthToUser",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_cid",
				"type": "uint256"
			}
		],
		"name": "withdrawGasRecovery",
		"outputs": [],
		"stateMutability": "nonpayable",
		"type": "function"
	},
	{
		"stateMutability": "payable",
		"type": "receive"
	},
	{
		"inputs": [],
		"name": "admin",
		"outputs": [
			{
				"internalType": "address",
				"name": "",
				"type": "address"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"name": "campaigns",
		"outputs": [
			{
				"internalType": "address payable",
				"name": "organizationAddress",
				"type": "address"
			},
			{
				"internalType": "string",
				"name": "organizationName",
				"type": "string"
			},
			{
				"internalType": "uint256",
				"name": "totalFund",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "totalGasSubsidized",
				"type": "uint256"
			},
			{
				"internalType": "uint256",
				"name": "totalDisbursed",
				"type": "uint256"
			},
			{
				"internalType": "bool",
				"name": "isActive",
				"type": "bool"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [],
		"name": "exchangePool",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	},
	{
		"inputs": [
			{
				"internalType": "uint256",
				"name": "_cid",
				"type": "uint256"
			}
		],
		"name": "getAvailableBalance",
		"outputs": [
			{
				"internalType": "uint256",
				"name": "",
				"type": "uint256"
			}
		],
		"stateMutability": "view",
		"type": "function"
	}
]

